{{- if and .Values.ingress.enabled (eq .Values.ingress.className "codetogether-nginx") -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: codetogether-nginx
spec:
  controller: k8s.io/ingress-nginx
{{- end }}