{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: {{ .Values.ingress.className }}
spec:
  controller: {{ .Values.ingress.controllerValue }}
{{- end }}
