{{- if and .Values.proxy.enabled .Values.proxy.uri (not .Values.proxy.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.proxy.secretName" . }}
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  proxy-uri: {{ .Values.proxy.uri | b64enc | quote }}
{{- end }}
