apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-ssl
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.locatorCentral.database.sslEnabled true }}
  key: {{ .Values.locatorCentral.database.sslKey | b64enc | quote }}
  cert: {{ .Values.locatorCentral.database.sslCert | b64enc | quote }}
  ca: {{ .Values.locatorCentral.database.sslCA | b64enc | quote }}
  {{- end -}}