{{- if .Values.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-sso
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  provider: {{ .Values.sso.provider | b64enc | quote }}
  systemBaseUrl: {{ .Values.sso.systemBaseUrl | b64enc | quote }}
  clientID: {{ .Values.sso.clientID | b64enc | quote }}
  clientSecret: {{ .Values.sso.clientSecret | b64enc | quote }}
{{- end }}
