apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-coturn
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.av.stunServers.secret | b64enc | quote }}
