{{- if eq .Values.imageCredentials.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
