apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-license
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  licensee: {{ .Values.license.licensee | b64enc | quote }}
  max_connections: {{ .Values.license.maxConnections | b64enc | quote }}
  expiration: {{ .Values.license.expiration | b64enc | quote }}
  signature: {{ .Values.license.signature | b64enc | quote }}
