apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetogether.fullname" . }}-ssl
  labels:
    {{- include "codetogether.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.locatorCentral.database.sslKey }}
  key: {{ .Values.locatorCentral.database.sslKey | b64enc | quote }}
  {{- end -}}
  {{- if .Values.locatorCentral.database.sslCert }}
  cert: {{ .Values.locatorCentral.database.sslCert | b64enc | quote }}
  {{- end -}}
  {{- if .Values.locatorCentral.database.sslCA }}
  ca: {{ .Values.locatorCentral.database.sslCA | b64enc | quote }}
  {{- end -}}