apiVersion: v1
entries:
  CodeTogether:
  - apiVersion: v2
    appVersion: 4.1.2
    created: "2021-08-11T11:23:40.912946318-05:00"
    description: CodeTogether is used to live share IDEs and coding sessions.
    digest: d1d3b503c89e2cbf5929c078fc96b27a386b664a2535c060f392ce288993e0ca
    home: https://www.codetogether.com
    icon: https://www.codetogether.com/wp-content/uploads/2020/02/codetogether-circle-128.png
    keywords:
    - codetogether
    - collaborative
    - pair
    - programming
    maintainers:
    - email: info@codetogether.com
      name: Genuitec, LLC
    name: CodeTogether
    type: application
    urls:
    - CodeTogether-1.0.1.tgz
    version: 1.0.1
generated: "2021-08-11T11:23:40.91187734-05:00"
